/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:d3cab7d8-0043-4ab0-92b6-3a0815fb0356",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_7qy4MFUb7",
    "aws_user_pools_web_client_id": "3c8m9nm2mvr6k2a0qgbotp64b1",
    "oauth": {}
};


export default awsmobile;
